### ISSUE TITLE
WP 6.1.1

### ISSUE THREAD

**Issue by vattlescout** [scouternasetjanster/wordpress-scoutnet#1]
Planer på att åtgärda detta script för WP 6.1.1?

Fick in tillägget och det fungerar bra i många delar men inte alla delar...
Se bifogad fil för att förstå bättre vad som inte fungerar - får alltså inte valen för att peka en egen API-koppling mot ID etc...
![API-koppling](https://user-images.githubusercontent.com/56027300/222105435-6cf21f39-5209-4da7-9b0a-1a6958631684.png)

**Comment by webbmastern** [comment]
@vattlescout Återkom gärna om det funkar nu för dig så att vi kan stänga denna issue.
Ny instruktion finns på https://github.com/Scouterna/WP-Shortcodes-for-Scoutnet#readme
Importera json-filen enligt instruktionen så borde det fungera.

**Comment by vattlescout** [comment]
Nu får jag upp valen, ska testa att det fungerar också under morgondagen.
